### PR TITLE
fix: Correct color box pop-up position

### PR DESCRIPTION
**Pull request by missingtears**

### CODE REVIEW

**Comment by willeastcott** [comment]
Thanks for the PR! Can you add a PR description please? I'm particularly interested in what scenario the current picker positioning breaks.

**Comment by missingtears** [comment]
image
When the color control is on the right side of the page, the position of the pop-up box is reduced by the width of the mask, and it moves to the far left.

**Review by willeastcott — APPROVED** [review]

**Comment by willeastcott** [comment]
Thanks for the fix! 🙏

**Comment by willeastcott** [comment]
@missingtears This is now deployed as part of [v4.4.0](https://github.com/playcanvas/pcui/releases/tag/v4.4.0).

**Pull request merged**
