### PR TITLE
Expose LabelGroup

### PR DESCRIPTION
**Pull request by vkalpias**
This PR exposes the LabelGroup in PCUI

image

### CODE REVIEW

**Review by slimbuck — APPROVED** [review]
LGTM, but you might want to wait for @ellthompson 's approval too!

**Comment by mvaligursky** [comment]
screenshot please!

**Comment by willeastcott** [comment]
I notice this moves pcui to version 1.1.9. But NPM is still on 1.1.5. Have we been neglecting to publish to NPM as we go?

**Comment by vkalpias** [comment]
> screenshot please!

done

**Comment by vkalpias** [comment]
> I notice this moves pcui to version 1.1.9. But NPM is still on 1.1.5. Have we been neglecting to publish to NPM as we go?

yeah

**Comment by vkalpias** [comment]
> > I notice this moves pcui to version 1.1.9. But NPM is still on 1.1.5. Have we been neglecting to publish to NPM as we go?
> 
> yeah

mainly because I'm always forgetting how to do that

**Comment by willeastcott** [comment]
`npm publish` 😆

**Pull request merged**
