### PR TITLE
Embedded font icons

### PR DESCRIPTION
**Pull request by ellthompson**
The PlayCanvas font icons are currently loaded via url. This PR instead embeds them in the application as base64 encoded strings.

### CODE REVIEW

**Review by yaustar — APPROVED** [review]
LGTM

**Comment by slimbuck** [comment]
does this result in a much bigger download?

**Comment by Maksims** [comment]
Shouldn't font files be in the directory as normal files? This can lead to longer compilation times for scss.

**Comment by ellthompson** [comment]
@Maksims I'm not sure it's a good idea to include fonts via a relative path in a JS library package. Users will be importing bundled components in JS, which internally contain relative path references to font files in their bundled css. The onus will be on them to copy these font files over into the right location relative to their bundled JS application.

Embedded assets or absolute urls to assets seem like safer options to me. The negative of embedding assets you've mentioned and I agree with. The negative of absolute urls is tying an open source library package to a particular web server.

**Comment by Maksims** [comment]
It's a complex enough library, that is not a single JS file, so developers definitely have their build processes. It's worth checking out how other libraries tackle fonts. And I'm certainly sure, it is not embedding them in CSS as this leads to loading stalls.

**Comment by ellthompson** [comment]
We've decided to go ahead with this change. The impact of loading a b64 encoded font file looks to be negligible but we'll assess if it begins to have an impact in the longer term.

**Pull request merged**
