### PR TITLE
fix: In shadow DOM, The target obtained is shadowRoot

### PR DESCRIPTION
**Pull request by missingtears**
image

### CODE REVIEW

**Comment by willeastcott** [comment]
Hi. Thanks very much for this pull request. I'm not quite sure what this is addressing. Can you provide a little more detail please?

**Comment by missingtears** [comment]
When I use SelectInput in the Web Components component and select the dropdown option, it cannot update the current value value. Because evt.target obtains the shadowRoot, not the select option, it is closed. By modifying it, it can be obtained in both the shadow DOM and outside;

**Comment by missingtears** [comment]
image

**Comment by missingtears** [comment]
image

**Review by willeastcott — APPROVED** [review]

**Comment by willeastcott** [comment]
Thanks for the PR!

**Pull request merged**
