### PR TITLE
Fix constructors and their arguments for JSDoc / pcui.d.ts

### PR DESCRIPTION
**Pull request by kungfooman**
This PR is improving on many constructors, so end users in TypeScript can have Intellisense:

image

The `pcui.d.ts` resembles the types as good as it gets based on inheritance:

image

However, I think I tried everything I could imagine in JSDoc to make this happen without patching the `pcui.d.ts` via `tsd.js`, but I couldn't find a way, so I introduced a little "meta syntax" e.g. `VectorInputArgs__extends__ElementArgs`, which is patched via RegEx into something like `VectorInputArgs extends ElementArgs` later... it looks clunky in JSDoc, but gets the job done for representing the type hierarchies in `pcui.d.ts`.

### CODE REVIEW

**Comment by yaustar** [comment]
It's arguable that we should be making actual classes for the args that are passed instead rather than trying to solve it with JSDocs?

**Comment by kungfooman** [comment]
> It's arguable that we should be making actual classes for the args that are passed instead rather than trying to solve it with JSDocs?

Good idea, I just tested around with:

```js
/**
 * @name ElementArgs
 * @class
 * @classdesc The base class for all element arguments.
 * @property {string} [id] - The desired id for the Element HTML node.
 * @property {string|string[]} [class] - The CSS class or classes we want to add to the element.
 * @property {boolean} [isRoot] - If true then this is the root element. Set this to true for the topmost Element in your page.
 * @property {boolean} [enabled] - Gets / sets whether the Element or its parent chain is enabled or not. Defaults to true.
 * @property {HTMLElement} [dom] - The DOM element that this pcui.Element wraps.
 * @property {boolean} [ignoreParent] - Gets / sets whether the Element will ignore parent events & variable states.
 * @property {number} [width] - Gets / sets the width of the Element in pixels. Can also be an empty string to remove it.
 * @property {number} [height] - Gets / sets the height of the Element in pixels. Can also be an empty string to remove it.
 * @property {number} [tabIndex] - Gets / sets the tabIndex of the Element.
 * @property {BindingBase} [binding] - Gets / sets the Binding object for the element.
 */

export class ElementArgs {
}
```

and

```js
/**
 * @name LabelArgs
 * @class
 * @classdesc The class for all Label arguments extending ElementArgs.
 * @property {boolean} [unsafe] - If true then the innerHTML property will be used to set the text. Otherwise textContent will be used instead.
 * @property {boolean} [nativeTooltip] - If true then use the text of the label as the native HTML tooltip.
 * @property {boolean} [allowTextSelection] - If true then the label can be clicked to select text.
 * @property {string} [text] - The text of the Label.
 * @property {string} [value] - The text of the Label, used when `text` is not set.
 */
class LabelArgs extends ElementArgs {

}
```

and it seems to work without any `__extends__` hack, I can fix the PR for that tomorrow, thanks for the idea! 💡

**Comment by kungfooman** [comment]
For my sake this is as good as it gets now:

image

The entire arguments type hierarchy is represented in `pcui.d.ts` without any JSDoc hacks (anymore).

**Comment by yaustar** [comment]
We are going to have a discussion internally about this as this could affect performance, how the docs are generated/laid out/readability and consistently. 

Arguably, it would be great to have the arguments listing on the same page as the constructor in the docs but also appreciate that there is a need for having the type listing and intellisense

**Comment by yaustar** [comment]
Looking at JSDocs, what we have should produce the correct typedefs
https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#typedef-callback-and-param
image

Maybe there is something wrong with our tsd generation?

**Comment by kungfooman** [comment]
> Looking at JSDocs, what we have should produce the correct typedefs

JSDoc seems useless when it comes to more involved types, as `@augments` / `@extends` is just ignored. What that means for the typical class that inherits from either `Element` (10 attributes) or `Container` (inherited 10 attributes from `Element` + 3 custom ones) is that e.g. `TreeViewItem` (which inherits from `Container`) would end up with 4 attributes only, even tho through inheritance it should have 17 (default ones like `enabled`, `width`, `height` etc.)... making it less useful for an end user relying on Intellisense.

I am sure JSDoc or whatever libraries it relies on can be fixed, but that is so involved I would rather ditch JSDoc and use TypeScript directly or write my own parser, so at least I would know where it fails 😅 

A quick search shows lots of open issues, some dating back to 2012 and are still open/unresolved: https://www.google.com/search?q=jsdoc+ignores+extends

**Comment by willeastcott** [comment]
Agreed. Thanks for submitting this @kungfooman but it's definitely been superseded by the migration to TypeScript.

**Pull request closed without merging**
